ROOM_CATEGORIES: 
  - Bedroom
  - Office
  - Living_Room
  - Dining_Room

OBJECT_CATEGORIES: 
  - kitchen_cabinet
  - refrigerator
  - desk
  - office_chair
  - coffee_table
  - television
  - tv_stand
  - wardrobe_cabinet
  - door
  - stand
  - dresser
  - plant
  - table_and_chair
  - dressing_table
  - chair
  - sofa
  - armchair
  - game_table
  - shelving
  - bookshelf
  - double_bed
  - dishwasher
  - floor_lamp
  - dining_table
  - range_oven
  - bunker_bed
  - trash_can
  - dryer
  - table
  - ottoman
  - single_bed
  - washer
  # additional objects starting here
  - fish_tank
  - piano
  - table_lamp
  - rug
  - food_processor
  - coffee_machine
  - microwave
  - iron
  - vacuum_cleaner
  - cutting_board
  - glass
  - bottle,
  - vase
  - toy
  - chessboard
  - playstation
  - decoration
  - column
  - fence
  - outdoor_lamp
  - grill
  - heater
  - piano
  - knife_rack
  - utensil_holder
  - goal_post
  - outdoor_seating
  - kitchen_set
  - baby_bed
  - storage_bench
  # you can specify this to filter objects

INTERACTABLE:
  - kitchen_cabinet
  - refrigerator
  - desk
  - coffee_table
  - tv_stand
  - tv
  - wardrobe_cabinet
  - door
  - stand
  - nightstand
  - sofa_chair
  - minisofa
  - dresser
  - dressing_table
  - drawer
  - cabinet
  - shoes_cabinet
  - sofa
  - game_table
  - shelving
  - bookshelf
  - double_bed
  - dishwasher
  - dining_table
  - range_oven
  - bunker_bed
  - bed
  - dryer
  - table
  - single_bed
  - washer

TASK_RELATED:
  - kitchen_cabinet
  - desk
  - coffee_table
  - television
  - tv_stand
  - wardrobe_cabinet
  - dresser
  - plant
  - dressing_table
  - piano
  - shoes_cabinet
  - sofa
  - armchair
  - game_table
  - shelving
  - baby_bed
  - bookshelf
  - double_bed
  - dishwasher
  - food_processor
  - dining_table
  - trash_can
  - dryer
  - table
  - ottoman
  - single_bed
  - washer
  - safe
  - storage_bench